// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
    "default": {
    "tree-view": {
      name: "tree-view",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/tree-view")),
      files: ["registry/default/extension/tree-view-api.tsx"],
    },
    "file-upload": {
      name: "file-upload",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/file-upload")),
      files: ["registry/default/extension/file-upload.tsx"],
    },
    "fancy-multi-select": {
      name: "fancy-multi-select",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/fancy-multi-select")),
      files: ["registry/default/extension/multi-select-api.tsx"],
    },
    "otp-input": {
      name: "otp-input",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/otp-input")),
      files: ["registry/default/extension/otp-input.tsx"],
    },
    "carousel": {
      name: "carousel",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/carousel")),
      files: ["registry/default/extension/carousel.tsx"],
    },
    "breadcrumbs": {
      name: "breadcrumbs",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/breadcrumbs")),
      files: ["registry/default/extension/breadcrumbs.tsx"],
    },
    "image-carousel-upload": {
      name: "image-carousel-upload",
      type: "components:extension",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/extension/image-carousel-upload")),
      files: ["registry/default/extension/image-carousel-upload.tsx"],
    },
    "tree-view-example": {
      name: "tree-view-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/tree-view-example")),
      files: ["registry/default/examples/tree-view-example.tsx"],
    },
    "file-upload-example": {
      name: "file-upload-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/file-upload-example")),
      files: ["registry/default/examples/file-upload-example.tsx"],
    },
    "fancy-multi-select-example": {
      name: "fancy-multi-select-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/fancy-multi-select-example")),
      files: ["registry/default/examples/fancy-multi-select-example.tsx"],
    },
    "otp-input-example": {
      name: "otp-input-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/otp-input-example")),
      files: ["registry/default/examples/otp-input-example.tsx"],
    },
    "carousel-example": {
      name: "carousel-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/carousel-example")),
      files: ["registry/default/examples/carousel-example.tsx"],
    },
    "breadcrumbs-example": {
      name: "breadcrumbs-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/breadcrumbs-example")),
      files: ["registry/default/examples/breadcrumbs-example.tsx"],
    },
    "image-carousel-upload-example": {
      name: "image-carousel-upload-example",
      type: "components:example",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/example/image-carousel-upload-example")),
      files: ["registry/default/examples/image-carousel-upload-example.tsx"],
    },
  },
}
