// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type docs = Collections['docs']['schema']['_output']
export declare const docs: docs[]
